spring:
  datasource:
    url: ${/myapp/db/url}
    username: ${/myapp/db/username}
    password: ${/myapp/db/password}
  jpa:
    hibernate:
      ddl-auto: update

info:
  team-name: ${/myapp/team-name}